### PR TITLE
What's new in Seaography 0.3.0

### PR DESCRIPTION
**Pull request by billy1624**

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @karatakis, feel free to edit the blog post. We're going to merge it tomorrow :)

**Comment by billy1624** [comment]
I drafted the release blog post on behalf of you and put you as the author, so you may well take a look. @karatakis

**Comment by karatakis** [comment]
Amazing work @billy1624. It covers everything :smile:

**Comment by billy1624** [comment]
Btw I submitted this to TWIR https://github.com/rust-lang/this-week-in-rust/pull/3858

**Pull request merged**
