### PR TITLE
0.5.x Docs - 1

### PR DESCRIPTION
**Pull request by billy1624**
We should execute the following command to tag 0.5.x docs before merging this into master

```sh
npm run docusaurus docs:version 0.5.x
```

REF: https://docusaurus.io/docs/versioning#directory-structure

### CODE REVIEW

**Comment by billy1624** [comment]
I guess we should also update the examples listed here. @tyt2y3 

image

**Comment by tyt2y3** [comment]
Yes

**Comment by billy1624** [comment]
> Yes

Updated

**Comment by tyt2y3** [comment]
The problem is I reverted `save` Return `Model`

**Comment by billy1624** [comment]
> The problem is I reverted `save` return `Model` `save` still returns `ActiveModel`

Which page in fault?

**Comment by billy1624** [comment]
Upgrade to docusaurus 2.0.0-beta.14 to fix the anchor link issue. Now it will bring you to the page and scroll to the corresponding header tag.
https://github.com/facebook/docusaurus/issues/2399

**Comment by tyt2y3** [comment]
> > The problem is I reverted `save` return `Model` `save` still returns `ActiveModel`
> 
> 
> 
> Which page in fault?

We need to update all code examples

**Comment by tyt2y3** [comment]
> Upgrade to docusaurus 2.0.0-beta.14 to fix the anchor link issue. Now it will bring you to the page and scroll to the corresponding header tag.
> 
> https://github.com/facebook/docusaurus/issues/2399

What's the consequences then?

**Comment by billy1624** [comment]
> > Upgrade to docusaurus 2.0.0-beta.14 to fix the anchor link issue. Now it will bring you to the page and scroll to the corresponding header tag.
> > [facebook/docusaurus#2399](https://github.com/facebook/docusaurus/issues/2399)
> 
> What's the consequences then?

Major changes are... others seems unchanged
- Click on header link will bring you to header tag
- Color scheme changed

Old: https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime/
New: https://deploy-preview-16--seaql.netlify.app/seaorm/docs/install-and-config/database-and-async-runtime/

You can check the changelog here https://github.com/facebook/docusaurus/blob/main/CHANGELOG.md

**Comment by billy1624** [comment]
> > > The problem is I reverted `save` return `Model` `save` still returns `ActiveModel`
> > 
> > 
> > Which page in fault?
> 
> We need to update all code examples

All double checked

**Pull request merged**
