### PR TITLE
refactor: move bakery schema to intro for better visibility

### PR DESCRIPTION
**Pull request by cemremengu**
Move bakery schema to intro for better visibility. It is currently referred under relation but used starting from the beginning of tutorial.

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Hey @cemremengu, thanks!! I think it's better to move the ER diagram to the beginning of relation section. What do you think?

**Comment by cemremengu** [comment]
I choose introduction because almost all examples throughout the tutorial use the cake schema. So if a users don't read the relation section, they will be confused about the the entities.

Though I agree that if it is going to be in the relation section it should be the first item. 

It is up to you I am fine with both decisions.

**Comment by billy1624** [comment]
Hey @cemremengu, I'll move the page to the front of relation section.

**Comment by tyt2y3** [comment]
Sadly this is still a confusion, because we have two different bakery schema in SeaORM test suite, one in unit test and one in integration tests, and I think the tests_cfg one is being used in most part of the documentation, so we have to generate a different ER diagram indeed.

**Comment by tyt2y3** [comment]
Basic schema was added https://github.com/SeaQL/seaql.github.io/commit/1f92d6d5f94d86136a557bd565fe56e5b296d43a

**Comment by billy1624** [comment]
Thanks!! @tyt2y3

**Pull request merged**
