### PR TITLE
What's new in SeaORM 0.10.1

### PR DESCRIPTION
**Pull request by tyt2y3**

### CODE REVIEW

**Comment by billy1624** [comment]
Hey @tyt2y3, I think it's the time to merge and release this

**Comment by billy1624** [comment]
And submit this to TWIR

**Comment by tyt2y3** [comment]
Sad I don't seem to be able to figure out a more illustrative example for GAT

**Comment by tyt2y3** [comment]
This definitely compiles, so the original problem is a lot more subtle

**Pull request merged**
