### PR TITLE
Add Nix installation instructions

### PR DESCRIPTION
**Pull request by lucperkins**
## Adds

- Installation instructions for installing the Sea ORM CLI using Nix/Nixpkgs (I'm in the process of adding a [`sea-orm-cli`](https://github.com/NixOS/nixpkgs/pull/183971/files) package). This PR, if accepted, should be merged only when that lands.

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Hey @lucperkins, Thanks for adding `sea-orm-cli` to Nix/Nixpkgs. I'm not familiar with Nix/Nixpkgs. I wonder what we need to do if we released new version of `sea-orm-cli` in the future?

**Comment by lucperkins** [comment]
@billy1624 It's pretty simple:

1. Fork `NixOS/nixpkgs` and install Nix locally
2. Update the `version` field in the file I added in the PR above
3. From the root of `nixpkgs`, run `nix-build -A sea-orm-cli`. That will fail because the `sha256` will be wrong for the new version, but the log output will tell you what the correct new SHA is.
4. Provide the correct new SHA and run the `nix-build -A sea-orm-cli` command again.
5. If that's successful, submit a PR with the changes, just make sure to name your PR in this format `sea-orm-cli: PREVIOUS-VERSION -> NEW-VERSION`, so something like `sea-orm-cli: 2.3.4 -> 2.3.5`.

**Comment by tyt2y3** [comment]
I really liked the idea of Nix and I appreciate that the package is apparently on Nix, but since those packages are not released by us I don't think it's responsible to endorse them

**Comment by lucperkins** [comment]
I'm not sure I really understand the objection, as inclusion in Nixpkgs is the standard way to release packages in the Nix community. But that's your prerogative.

**Pull request closed without merging**
